import AboutPage from '@/components/pages/AboutPage'
import { Sheet } from '@/components/ui/sheet'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'About',
    description: 'Generated by create next app',
    icons: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👨‍💻</text></svg>"
}

export default function Home() {
    return (
        <>
            <Sheet>
                <AboutPage />
            </Sheet>
        </>
    )
}
